variable "network_autostart" {
  description = "Whether to autostart the libvirt network"
  type        = bool
  default     = true
}

variable "network_name" {
  description = "Name of the libvirt network"
  type        = string
  default     = "default"
}

variable "network_mode" {
  description = "Mode of the libvirt network (e.g., nat, route, bridge, open, private)"
  type        = string
  default     = "nat"
}

variable "network_domain" {
  description = "Domain of the libvirt network"
  type        = string
  default     = null
}

variable "network_cidr" {
  description = "CIDR blocks for the libvirt network IP configuration"
  type        = list(string)
  default     = ["192.168.122.0/24"]
}

variable "network_bridge" {
  description = "Bridge name for the libvirt network (optional, generated by libvirt if not specified)"
  type        = string
  default     = null
}

variable "network_mtu" {
  description = "MTU size for the libvirt network"
  type        = number
  default     = 1500
}

variable "network_dns_enabled" {
  description = "Whether DNS is enabled for the libvirt network"
  type        = bool
  default     = false
}

variable "network_dns_local" {
  description = "Whether DNS domain is local-only for the libvirt network"
  type        = bool
  default     = false
}

variable "network_dhcp_enabled" {
  description = "Whether DHCP is enabled for the libvirt network"
  type        = bool
  default     = false
}

variable "network_dhcp_range_start" {
  description = "DHCP range start IP address"
  type        = string
  default     = null
}

variable "network_dhcp_range_end" {
  description = "DHCP range end IP address"
  type        = string
  default     = null
}

variable "network_dns_entries" {
  description = "Map of DNS entries for the libvirt network (hostname = IP address)"
  type        = map(string)
  default     = {}
}

variable "network_routes" {
  description = "Map of static routes for the libvirt network (CIDR = gateway, e.g., '10.0.0.0/24' = '10.0.0.1')"
  type        = map(string)
  default     = {}
}

variable "network_dns_srv_records" {
  description = "List of SRV records to add to libvirt network DNS configuration"
  type = list(object({
    service  = string
    protocol = string
    domain   = string
    target   = string
    port     = number      # Changed from string to number
    priority = number      # Changed from string to number
    weight   = number      # Changed from string to number
  }))
  default = []
}

variable "network_dnsmasq_options" {
  type        = list(string)
  description = "List of dnsmasq options. Each element can be 'value' or 'key=value'"
  default     = []
}
